apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'kube-state-metrics'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: kube-system
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io/name]
            action: keep
            regex: kube-state-metrics
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: http-metrics

      - job_name: 'health-check-service'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: health-check-service
          - source_labels: [__meta_kubernetes_service_port_name]
            action: keep
            regex: http
