apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-secondary1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /minikube-host/secondary1
