apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_HOST: bXlzcWw=
  DB_USER: cm9vdA==
  DB_NAME: ZGVtbw==
  DB_PASSWORD: YWRtaW4xMjM0NSQ=  # base64 кодированное значение "admin12345$"
  mysql-root-password: YWRtaW4xMjM0NSQ=  # base64 кодированное значение "admin12345$"
  mysql-user: ZGVtbw==  # base64 кодированное значение "demo"
  mysql-password: MTIzNDU2  # base64 кодированное значение "123456"
  mysql-database: ZGVtbw==  # base64 кодированное значение "demo"
